# SETUP
baseurl = "/"
DefaultContentLanguage = "en"
publishdir = "public"
canonifyUrls = "true"
disableKinds = ["RSS","taxonomy","taxonomyTerm"] # disable hugo's content that we don't need...

title = "Wedding - Luna & Nathan"

[author]
    name = "Luna & Nathan"
    email = "wedding@kuikgyalokay.com"

[params]
    description = "Informational site about our wedding" # page description -> see ./layouts/partials/head.html
    images = [] #add images here as "img/name.ext" (points to s./static/img/) to populate the default og and twitter <meta> attributes -> see ./layouts/partials/head.html

# these items will be rendered 1. into a tooltip in the navbar and 2. into the footer - consider that there's limited space when adding more items -> see ./layouts/partials
[[params.social]]
    title = "Twitter"
    url = "https://twitter.com/#" # add your twitter handle
[[params.social]]
    title = "LinkedIn"
    url = "https://linkedin.com/company/#" # add your linkedin profile URL